---
- name: Create a database for Sonar.
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_db:
    name: "{{ sonar_postgres_database }}"
    encoding: UTF-8 
    state: present

- name: Create a sonar user.
  become: yes
  become_user: "{{ postgresql_user }}"
  postgresql_user:
    name: "{{ sonar_postgres_username }}"
    password: "{{ sonar_postgres_password }}"
    db: "{{ sonar_postgres_database }}"
    priv: "ALL"

- name: Configure SonarQube JDBC settings for Postgres.
  lineinfile:
    dest: /usr/local/sonar/conf/sonar.properties
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  notify: restart sonar
  with_items:
    - regexp: "^sonar.jdbc.username"
      line: "sonar.jdbc.username={{ sonar_postgres_username }}"
    - regexp: "^sonar.jdbc.password"
      line: "sonar.jdbc.password={{ sonar_postgres_password }}"
    - regexp: "^sonar.jdbc.url"
      line: "sonar.jdbc.url=jdbc:postgresql://{{ sonar_postgres_host }}:{{ sonar_postgres_port }}/{{ sonar_postgres_database }}"
    - regexp: "^sonar.web.context"
      line: "sonar.web.context={{ sonar_web_context }}"