---
# Let's rock on ALM
- name: Deploy Jenkins CI
  hosts: jenkins_server
  remote_user: vagrant
  become: yes

  roles:
    - geerlingguy.jenkins

- name: Deploy Nexus Server
  hosts: nexus_server
  remote_user: vagrant
  become: yes

  roles:
    - geerlingguy.java
    - savoirfairelinux.nexus3-oss

- name: Deploy Sonar Server
  hosts: sonar_server
  remote_user: vagrant
  become: yes

  roles:
    - wtanaka.unzip
    - zanini.sonar
